name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Run GoReleaser with Docker
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=validate
          install-only: false
          use-docker: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
